/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 9
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 7
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_jj_comment = 1,
  anon_sym_COLON = 2,
  anon_sym_LF = 3,
  sym_section_keyword = 4,
  sym_section_trailing = 5,
  sym__plain_line = 6,
  sym_source_file = 7,
  sym__line = 8,
  sym_section_header = 9,
  aux_sym_source_file_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_jj_comment] = "jj_comment",
  [anon_sym_COLON] = ":",
  [anon_sym_LF] = "\n",
  [sym_section_keyword] = "section_keyword",
  [sym_section_trailing] = "section_trailing",
  [sym__plain_line] = "_plain_line",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_section_header] = "section_header",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_jj_comment] = sym_jj_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LF] = anon_sym_LF,
  [sym_section_keyword] = sym_section_keyword,
  [sym_section_trailing] = sym_section_trailing,
  [sym__plain_line] = sym__plain_line,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_section_header] = sym_section_header,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_jj_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_section_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_section_trailing] = {
    .visible = true,
    .named = true,
  },
  [sym__plain_line] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_header = 1,
  field_trailing = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_header] = "header",
  [field_trailing] = "trailing",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
    {field_trailing, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == 'J') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_jj_comment);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_jj_comment);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_section_keyword);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_section_keyword);
      if (lookahead == 'J') ADVANCE(6);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_section_keyword);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__plain_line);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__plain_line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__plain_line);
      if (eof) ADVANCE(1);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == 'J') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__plain_line);
      if (eof) ADVANCE(1);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == 'J') ADVANCE(7);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(8);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 12},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_jj_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [sym_section_keyword] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(7),
    [sym__line] = STATE(2),
    [sym_section_header] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_jj_comment] = ACTIONS(5),
    [sym_section_keyword] = ACTIONS(7),
    [sym__plain_line] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_section_header] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_jj_comment] = ACTIONS(13),
    [sym_section_keyword] = ACTIONS(7),
    [sym__plain_line] = ACTIONS(15),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_section_header] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_jj_comment] = ACTIONS(19),
    [sym_section_keyword] = ACTIONS(22),
    [sym__plain_line] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(30), 1,
      anon_sym_LF,
    ACTIONS(28), 2,
      ts_builtin_sym_end,
      sym_jj_comment,
    ACTIONS(32), 2,
      sym_section_keyword,
      sym__plain_line,
  [12] = 2,
    ACTIONS(34), 2,
      ts_builtin_sym_end,
      sym_jj_comment,
    ACTIONS(36), 2,
      sym_section_keyword,
      sym__plain_line,
  [21] = 1,
    ACTIONS(38), 1,
      anon_sym_COLON,
  [25] = 1,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
  [29] = 1,
    ACTIONS(42), 1,
      sym_section_trailing,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 12,
  [SMALL_STATE(6)] = 21,
  [SMALL_STATE(7)] = 25,
  [SMALL_STATE(8)] = 29,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 3, 0, 1),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 3, 0, 1),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 4, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 4, 0, 1),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [40] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jujutsu(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
