/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 17
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_jj_comment = 1,
  anon_sym_LF = 2,
  sym_section_keyword = 3,
  sym_section_trailing = 4,
  sym_file_status = 5,
  sym_empty_marker = 6,
  sym_bookmark = 7,
  sym_commit_id = 8,
  sym_change_id = 9,
  sym_graph_char = 10,
  sym__alnum_run = 11,
  sym__content_text = 12,
  sym_source_file = 13,
  sym__line = 14,
  sym_section_header = 15,
  sym_file_status_line = 16,
  sym__content_line = 17,
  sym__blank_line = 18,
  sym__content_atom = 19,
  aux_sym_source_file_repeat1 = 20,
  aux_sym_file_status_line_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_jj_comment] = "jj_comment",
  [anon_sym_LF] = "\n",
  [sym_section_keyword] = "section_keyword",
  [sym_section_trailing] = "section_trailing",
  [sym_file_status] = "file_status",
  [sym_empty_marker] = "empty_marker",
  [sym_bookmark] = "bookmark",
  [sym_commit_id] = "commit_id",
  [sym_change_id] = "change_id",
  [sym_graph_char] = "graph_char",
  [sym__alnum_run] = "_alnum_run",
  [sym__content_text] = "_content_text",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_section_header] = "section_header",
  [sym_file_status_line] = "file_status_line",
  [sym__content_line] = "_content_line",
  [sym__blank_line] = "_blank_line",
  [sym__content_atom] = "_content_atom",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_file_status_line_repeat1] = "file_status_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_jj_comment] = sym_jj_comment,
  [anon_sym_LF] = anon_sym_LF,
  [sym_section_keyword] = sym_section_keyword,
  [sym_section_trailing] = sym_section_trailing,
  [sym_file_status] = sym_file_status,
  [sym_empty_marker] = sym_empty_marker,
  [sym_bookmark] = sym_bookmark,
  [sym_commit_id] = sym_commit_id,
  [sym_change_id] = sym_change_id,
  [sym_graph_char] = sym_graph_char,
  [sym__alnum_run] = sym__alnum_run,
  [sym__content_text] = sym__content_text,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_section_header] = sym_section_header,
  [sym_file_status_line] = sym_file_status_line,
  [sym__content_line] = sym__content_line,
  [sym__blank_line] = sym__blank_line,
  [sym__content_atom] = sym__content_atom,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_file_status_line_repeat1] = aux_sym_file_status_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_jj_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_section_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_section_trailing] = {
    .visible = true,
    .named = true,
  },
  [sym_file_status] = {
    .visible = true,
    .named = true,
  },
  [sym_empty_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_bookmark] = {
    .visible = true,
    .named = true,
  },
  [sym_commit_id] = {
    .visible = true,
    .named = true,
  },
  [sym_change_id] = {
    .visible = true,
    .named = true,
  },
  [sym_graph_char] = {
    .visible = true,
    .named = true,
  },
  [sym__alnum_run] = {
    .visible = false,
    .named = true,
  },
  [sym__content_text] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [sym_file_status_line] = {
    .visible = true,
    .named = true,
  },
  [sym__content_line] = {
    .visible = false,
    .named = true,
  },
  [sym__blank_line] = {
    .visible = false,
    .named = true,
  },
  [sym__content_atom] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_status_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_header = 1,
  field_trailing = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_header] = "header",
  [field_trailing] = "trailing",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
    {field_trailing, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
};

static const TSCharacterRange sym_graph_char_character_set_1[] = {
  {'@', '@'}, {'~', '~'}, {0x2026, 0x2026}, {0x2500, 0x2500}, {0x2502, 0x2502}, {0x251c, 0x251c}, {0x2524, 0x2524}, {0x256d, 0x2570},
  {0x25c6, 0x25c6}, {0x25c9, 0x25c9}, {0x25cb, 0x25cb},
};

static const TSCharacterRange sym__content_text_character_set_1[] = {
  {0, '\t'}, {0x0b, '\''}, {')', '/'}, {':', '?'}, {'A', 'Z'}, {'\\', '`'}, {'{', '}'}, {0x7f, 0x2025},
  {0x2027, 0x24ff}, {0x2501, 0x2501}, {0x2503, 0x251b}, {0x251d, 0x2523}, {0x2525, 0x256c}, {0x2571, 0x25c5}, {0x25c7, 0x25c8}, {0x25ca, 0x25ca},
  {0x25cc, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym_section_trailing);
      if (eof) ADVANCE(44);
      if (lookahead == '(') ADVANCE(60);
      if (lookahead == 'J') ADVANCE(54);
      if (lookahead == '[') ADVANCE(57);
      if (lookahead == 'A' ||
          lookahead == 'D' ||
          lookahead == 'M' ||
          lookahead == 'R') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(91);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead)) ADVANCE(139);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == ')') ADVANCE(103);
      END_STATE();
    case 4:
      if (lookahead == ']') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(2);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(1);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'p') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(10);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 19:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'y') ADVANCE(3);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(137);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      if (eof) ADVANCE(44);
      ADVANCE_MAP(
        '\n', 48,
        '(', 145,
        'J', 142,
        '[', 149,
        'A', 141,
        'D', 141,
        'M', 141,
        'R', 141,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead)) ADVANCE(139);
      if (('B' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(146);
      if (lookahead != 0) ADVANCE(148);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_jj_comment);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_jj_comment);
      if (lookahead == '\n') ADVANCE(45);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '[' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_jj_comment);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_section_keyword);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ' ') ADVANCE(101);
      if (lookahead == ':') ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ')') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'J') ADVANCE(56);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= '[') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == ']') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'c') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'd') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'e') ADVANCE(65);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'e') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'e') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'i') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'm') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'n') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'o') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'o') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'p') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'p') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'r') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 's') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 's') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 't') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 't') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 't') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead == 'y') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(98);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(92);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(93);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(94);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(95);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(96);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(97);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(137);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(89);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_section_trailing);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_section_trailing);
      if (set_contains(sym_graph_char_character_set_1, 11, lookahead) ||
          lookahead == '(' ||
          ('0' <= lookahead && lookahead <= '9') ||
          lookahead == '[' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(99);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_section_trailing);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_file_status);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(55);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_file_status);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_empty_marker);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_bookmark);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_commit_id);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(105);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(106);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(107);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(108);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(109);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(110);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(111);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(112);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(114);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(115);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(116);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(117);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(118);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(119);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(120);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(121);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(122);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(123);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(124);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(125);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(126);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(127);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(128);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(129);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(130);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(131);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(132);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(133);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(134);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(135);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_commit_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_change_id);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(140);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_graph_char);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym__alnum_run);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead == ' ') ADVANCE(102);
      if (lookahead == ':') ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      if ((!eof && set_contains(sym__content_text_character_set_1, 17, lookahead))) ADVANCE(148);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'J') ADVANCE(144);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      if ((!eof && set_contains(sym__content_text_character_set_1, 17, lookahead))) ADVANCE(148);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      if ((!eof && set_contains(sym__content_text_character_set_1, 17, lookahead))) ADVANCE(148);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead == ':') ADVANCE(46);
      if (lookahead == ' ' ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(143);
      if ((!eof && set_contains(sym__content_text_character_set_1, 17, lookahead))) ADVANCE(148);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead == 'e') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym__content_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym__content_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      if (('g' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym__content_text);
      if ((!eof && set_contains(sym__content_text_character_set_1, 17, lookahead))) ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym__content_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != ']') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 43},
  [2] = {.lex_state = 43},
  [3] = {.lex_state = 43},
  [4] = {.lex_state = 43},
  [5] = {.lex_state = 43},
  [6] = {.lex_state = 43},
  [7] = {.lex_state = 43},
  [8] = {.lex_state = 43},
  [9] = {.lex_state = 43},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 43},
  [12] = {.lex_state = 43},
  [13] = {.lex_state = 43},
  [14] = {.lex_state = 43},
  [15] = {.lex_state = 100},
  [16] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_jj_comment] = ACTIONS(1),
    [sym_section_keyword] = ACTIONS(1),
    [sym_section_trailing] = ACTIONS(1),
    [sym_file_status] = ACTIONS(1),
    [sym_empty_marker] = ACTIONS(1),
    [sym_bookmark] = ACTIONS(1),
    [sym_commit_id] = ACTIONS(1),
    [sym_change_id] = ACTIONS(1),
    [sym_graph_char] = ACTIONS(1),
    [sym__alnum_run] = ACTIONS(1),
    [sym__content_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym__line] = STATE(2),
    [sym_section_header] = STATE(2),
    [sym_file_status_line] = STATE(2),
    [sym__content_line] = STATE(2),
    [sym__blank_line] = STATE(2),
    [sym__content_atom] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_jj_comment] = ACTIONS(5),
    [anon_sym_LF] = ACTIONS(5),
    [sym_section_keyword] = ACTIONS(7),
    [sym_file_status] = ACTIONS(9),
    [sym_empty_marker] = ACTIONS(11),
    [sym_bookmark] = ACTIONS(11),
    [sym_commit_id] = ACTIONS(11),
    [sym_change_id] = ACTIONS(13),
    [sym_graph_char] = ACTIONS(11),
    [sym__alnum_run] = ACTIONS(13),
    [sym__content_text] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym_section_header] = STATE(3),
    [sym_file_status_line] = STATE(3),
    [sym__content_line] = STATE(3),
    [sym__blank_line] = STATE(3),
    [sym__content_atom] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_jj_comment] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(17),
    [sym_section_keyword] = ACTIONS(7),
    [sym_file_status] = ACTIONS(9),
    [sym_empty_marker] = ACTIONS(11),
    [sym_bookmark] = ACTIONS(11),
    [sym_commit_id] = ACTIONS(11),
    [sym_change_id] = ACTIONS(13),
    [sym_graph_char] = ACTIONS(11),
    [sym__alnum_run] = ACTIONS(13),
    [sym__content_text] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym_section_header] = STATE(3),
    [sym_file_status_line] = STATE(3),
    [sym__content_line] = STATE(3),
    [sym__blank_line] = STATE(3),
    [sym__content_atom] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_jj_comment] = ACTIONS(21),
    [anon_sym_LF] = ACTIONS(21),
    [sym_section_keyword] = ACTIONS(24),
    [sym_file_status] = ACTIONS(27),
    [sym_empty_marker] = ACTIONS(30),
    [sym_bookmark] = ACTIONS(30),
    [sym_commit_id] = ACTIONS(30),
    [sym_change_id] = ACTIONS(33),
    [sym_graph_char] = ACTIONS(30),
    [sym__alnum_run] = ACTIONS(33),
    [sym__content_text] = ACTIONS(33),
  },
  [STATE(4)] = {
    [sym__content_atom] = STATE(6),
    [aux_sym_file_status_line_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(36),
    [sym_jj_comment] = ACTIONS(36),
    [anon_sym_LF] = ACTIONS(38),
    [sym_section_keyword] = ACTIONS(40),
    [sym_file_status] = ACTIONS(40),
    [sym_empty_marker] = ACTIONS(42),
    [sym_bookmark] = ACTIONS(42),
    [sym_commit_id] = ACTIONS(42),
    [sym_change_id] = ACTIONS(44),
    [sym_graph_char] = ACTIONS(42),
    [sym__alnum_run] = ACTIONS(44),
    [sym__content_text] = ACTIONS(44),
  },
  [STATE(5)] = {
    [sym__content_atom] = STATE(7),
    [aux_sym_file_status_line_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_jj_comment] = ACTIONS(46),
    [anon_sym_LF] = ACTIONS(48),
    [sym_section_keyword] = ACTIONS(50),
    [sym_file_status] = ACTIONS(50),
    [sym_empty_marker] = ACTIONS(52),
    [sym_bookmark] = ACTIONS(52),
    [sym_commit_id] = ACTIONS(52),
    [sym_change_id] = ACTIONS(54),
    [sym_graph_char] = ACTIONS(52),
    [sym__alnum_run] = ACTIONS(54),
    [sym__content_text] = ACTIONS(54),
  },
  [STATE(6)] = {
    [sym__content_atom] = STATE(8),
    [aux_sym_file_status_line_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_jj_comment] = ACTIONS(56),
    [anon_sym_LF] = ACTIONS(58),
    [sym_section_keyword] = ACTIONS(60),
    [sym_file_status] = ACTIONS(60),
    [sym_empty_marker] = ACTIONS(62),
    [sym_bookmark] = ACTIONS(62),
    [sym_commit_id] = ACTIONS(62),
    [sym_change_id] = ACTIONS(64),
    [sym_graph_char] = ACTIONS(62),
    [sym__alnum_run] = ACTIONS(64),
    [sym__content_text] = ACTIONS(64),
  },
  [STATE(7)] = {
    [sym__content_atom] = STATE(8),
    [aux_sym_file_status_line_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_jj_comment] = ACTIONS(66),
    [anon_sym_LF] = ACTIONS(68),
    [sym_section_keyword] = ACTIONS(70),
    [sym_file_status] = ACTIONS(70),
    [sym_empty_marker] = ACTIONS(62),
    [sym_bookmark] = ACTIONS(62),
    [sym_commit_id] = ACTIONS(62),
    [sym_change_id] = ACTIONS(64),
    [sym_graph_char] = ACTIONS(62),
    [sym__alnum_run] = ACTIONS(64),
    [sym__content_text] = ACTIONS(64),
  },
  [STATE(8)] = {
    [sym__content_atom] = STATE(8),
    [aux_sym_file_status_line_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_jj_comment] = ACTIONS(72),
    [anon_sym_LF] = ACTIONS(72),
    [sym_section_keyword] = ACTIONS(74),
    [sym_file_status] = ACTIONS(74),
    [sym_empty_marker] = ACTIONS(76),
    [sym_bookmark] = ACTIONS(76),
    [sym_commit_id] = ACTIONS(76),
    [sym_change_id] = ACTIONS(79),
    [sym_graph_char] = ACTIONS(76),
    [sym__alnum_run] = ACTIONS(79),
    [sym__content_text] = ACTIONS(79),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [sym_jj_comment] = ACTIONS(82),
    [anon_sym_LF] = ACTIONS(84),
    [sym_section_keyword] = ACTIONS(86),
    [sym_file_status] = ACTIONS(86),
    [sym_empty_marker] = ACTIONS(82),
    [sym_bookmark] = ACTIONS(82),
    [sym_commit_id] = ACTIONS(82),
    [sym_change_id] = ACTIONS(86),
    [sym_graph_char] = ACTIONS(82),
    [sym__alnum_run] = ACTIONS(86),
    [sym__content_text] = ACTIONS(86),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_jj_comment] = ACTIONS(56),
    [anon_sym_LF] = ACTIONS(56),
    [sym_section_keyword] = ACTIONS(60),
    [sym_file_status] = ACTIONS(60),
    [sym_empty_marker] = ACTIONS(56),
    [sym_bookmark] = ACTIONS(56),
    [sym_commit_id] = ACTIONS(56),
    [sym_change_id] = ACTIONS(60),
    [sym_graph_char] = ACTIONS(56),
    [sym__alnum_run] = ACTIONS(60),
    [sym__content_text] = ACTIONS(60),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_jj_comment] = ACTIONS(66),
    [anon_sym_LF] = ACTIONS(66),
    [sym_section_keyword] = ACTIONS(70),
    [sym_file_status] = ACTIONS(70),
    [sym_empty_marker] = ACTIONS(66),
    [sym_bookmark] = ACTIONS(66),
    [sym_commit_id] = ACTIONS(66),
    [sym_change_id] = ACTIONS(70),
    [sym_graph_char] = ACTIONS(66),
    [sym__alnum_run] = ACTIONS(70),
    [sym__content_text] = ACTIONS(70),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym_jj_comment] = ACTIONS(88),
    [anon_sym_LF] = ACTIONS(88),
    [sym_section_keyword] = ACTIONS(90),
    [sym_file_status] = ACTIONS(90),
    [sym_empty_marker] = ACTIONS(88),
    [sym_bookmark] = ACTIONS(88),
    [sym_commit_id] = ACTIONS(88),
    [sym_change_id] = ACTIONS(90),
    [sym_graph_char] = ACTIONS(88),
    [sym__alnum_run] = ACTIONS(90),
    [sym__content_text] = ACTIONS(90),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(92),
    [sym_jj_comment] = ACTIONS(92),
    [anon_sym_LF] = ACTIONS(92),
    [sym_section_keyword] = ACTIONS(94),
    [sym_file_status] = ACTIONS(94),
    [sym_empty_marker] = ACTIONS(92),
    [sym_bookmark] = ACTIONS(92),
    [sym_commit_id] = ACTIONS(92),
    [sym_change_id] = ACTIONS(94),
    [sym_graph_char] = ACTIONS(92),
    [sym__alnum_run] = ACTIONS(94),
    [sym__content_text] = ACTIONS(94),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(96),
    [sym_jj_comment] = ACTIONS(96),
    [anon_sym_LF] = ACTIONS(96),
    [sym_section_keyword] = ACTIONS(98),
    [sym_file_status] = ACTIONS(98),
    [sym_empty_marker] = ACTIONS(96),
    [sym_bookmark] = ACTIONS(96),
    [sym_commit_id] = ACTIONS(96),
    [sym_change_id] = ACTIONS(98),
    [sym_graph_char] = ACTIONS(96),
    [sym__alnum_run] = ACTIONS(98),
    [sym__content_text] = ACTIONS(98),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(100), 1,
      sym_section_trailing,
  [4] = 1,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 4,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_status_line, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_status_line, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_line, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__content_line, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_status_line, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_status_line, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_line, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__content_line, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_status_line_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_file_status_line_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_status_line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_file_status_line_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 2, 0, 1),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 2, 0, 1),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_header, 3, 0, 1),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_header, 3, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_status_line, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_file_status_line, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__content_line, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__content_line, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jujutsu(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
