vim.bo.commentstring = 'JJ: %s'

-- status.jj is regenerated by the server on every command; the user must never
-- edit it directly. log.jj keeps its first line (REVSET: header) editable, so
-- only status.jj gets the read-only treatment.
local name = vim.api.nvim_buf_get_name(0)
if name:match('/%.jj/badjuju/status%.jj$') then
  vim.bo.modifiable = false
  vim.bo.readonly = true
end

-- Reflect on-disk changes (the server rewrites these files behind our back).
vim.bo.autoread = true

require('badjuju.keymap').setup_for_buffer(0)
