vim.bo.commentstring = 'JJ: %s'

-- status.jujutsu is regenerated by the server on every command; the user must
-- never edit it directly. log.jujutsu keeps its first line (REVSET: header)
-- editable, so only status.jujutsu gets the read-only treatment.
local name = vim.api.nvim_buf_get_name(0)
if name:match('/%.jj/badjuju/status%.jujutsu$') then
  vim.bo.modifiable = false
  vim.bo.readonly = true
end

-- Reflect on-disk changes (the server rewrites these files behind our back).
vim.bo.autoread = true

require('badjuju.keymap').setup_for_buffer(0)
