[package]
name = "badjuju"
version = "0.1.1"
edition = "2024"

[[bin]]
name = "badjuju"
path = "src/main.rs"

[lib]
name = "badjuju"
path = "src/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1.46.1", features = ["io-std", "macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tower-lsp = "0.20.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
notify-debouncer-mini = "0.7.0"

[dev-dependencies]
tempfile = "3"
